Avoid crashing during shutdown of the package
Lombiq/Lombiq-Orchard-Visual-Studio-Extension pull request #31
Opened 2023-07-21 05:14 UTC by davkean

SwitchToMainThreadAsync throws OperationCancelledException if the specified cancellation token is signalled. This crashes Visual Studio if timer fires during Visual studio shutdown.

This has had 210 crashes in past 21 days.

2023-07-21 05:16 UTC, davkean commented
Diff is much easier to read if you hide whitespace changes: 
![image](https://github.com/Lombiq/Lombiq-Orchard-Visual-Studio-Extension/assets/1103906/adaedbff-b616-45dc-80e4-0f5d9d5604e8)

2023-08-21 06:55 UTC, davkean commented
Sorry to bother you @Piedone could I get a review on this and get this merged in?

2023-08-21 13:15 UTC, Piedone requested changes

2023-08-21 13:15 UTC, Piedone commented on Lombiq.Vsix.Orchard/Services/LogWatcher/LogFileWatcherBase.cs
>              }
```suggestion
            }
            catch (OperationCanceledException)
            {
                // We're being shutdown.
            }
```

2023-08-21 13:15 UTC, Piedone commented
Thank you for your valuable contribution!

Sorry for not replying earlier; the [Create Jira issues for community activities](https://github.com/Lombiq/Lombiq-Orchard-Visual-Studio-Extension/actions/workflows/create-jira-issues-for-community-activities.yml) workflow should've run and thus notified us about you opening this PR, I don't know why this didn't happen. The build didn't run for your code either, and while that should require an approval, there's no option to approve here... It seems something got messed up by GitHub Actions for this PR. This is the reason the code analyzers didn't tell you what I just did with my small remark.

Once you apply the code suggestion, please re-request review. Hopefully, the commit will now trigger the build workflow.

2023-08-21 13:17 UTC, Piedone commented
And yes, now it worked! Running the build now.

BTW do you use our extension for some tests in the VS team, or did you find this bug during your private work?

2023-08-21 13:20 UTC, davkean commented
Our telemetry data captured this crash, and I just investigated it. Thanks for getting on this.

2023-08-21 13:21 UTC, merged

2023-08-21 13:22 UTC, Piedone commented
I see, awesome! I don't think we'd have noticed this issue otherwise.

I'll do a release now too.