VSIX-65: Add support for Razor Pages to the Dependency Injector.
Lombiq/Lombiq-Orchard-Visual-Studio-Extension pull request #40
Opened 2024-06-25 19:39 UTC by DrewBrasher

Fix for issue https://github.com/Lombiq/Lombiq-Orchard-Visual-Studio-Extension/issues/39

2025-03-29 23:12 UTC, Piedone requested changes
I'm terribly sorry that nobody replied to you here or under your issue. There were some issues with notifications about issues and PRs that we normally get, and this project was caught right when it was in effect (fixed since). So, I just stumbled upon these now by chance.

Thank you for your contribution!

While this indeed handles Razor Pages, we mustn't forget that people can try to use the dependency injector in cshtml files of MVC projects too, where the injection should still fail. So, I'd modify the approach to only do this when `document.FullName` ends in `.cshtml.cs`.

2025-05-18 18:36 UTC, Piedone commented
Would you like to get back to this, @DrewBrasher?

2025-05-18 18:39 UTC, DrewBrasher commented
Yes. Sorry, I forgot about this.

2025-05-18 18:41 UTC, Piedone commented
Thank you!

2025-05-19 15:33 UTC, Piedone approved these changes
Thank you!

2025-05-19 15:38 UTC, merged